In [1]:
import pandas as pd

In [2]:
# %%
eval_df = pd.read_csv(
    "hf://datasets/bitext/Bitext-customer-support-llm-chatbot-training-dataset/"
    "Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv"
)

print(eval_df.shape)
print(eval_df["intent"].nunique())

(26872, 5)
27

In [3]:
# %%
eval_set = (
    eval_df
    .groupby("intent")
    .sample(n=1, random_state=42)
    .reset_index(drop=True)
)

print("Evaluation queries:", len(eval_set))

Evaluation queries: 27

In [4]:
eval_set

,flags,instruction,category,intent,response
0,BELN,I cannot afford purchase {{Order Number}},ORDER,cancel_order,I understand the financial constraints you are...
1,BKL,modify order {{Order Number}},ORDER,change_order,Thank you for bringing up the request to modif...
2,BIL,where do I correct my address?,SHIPPING,change_shipping_address,"To update your shipping address, you can go to..."
3,BILMZ,where can I see the temrination fees?,CANCEL,check_cancellation_fee,"Sure, I can help you with finding information ..."
4,BLQZ,i dont know what i need to do to find ibll #12588,INVOICE,check_invoice,I've realized you're unsure about the steps to...
5,BL,show me your payment options,PAYMENT,check_payment_methods,For sure! It's my pleasure to assist you in ex...
6,BI,can you show me in what cases can I ask to be ...,REFUND,check_refund_policy,I'm on it! I completely understand your desire...
7,BL,help making a customer reclamation against you...,FEEDBACK,complaint,I apologize for any inconvenience you have exp...
8,BIL,can I contact customer assistance?,CONTACT,contact_customer_service,Thank you for reaching out! I completely under...
9,BILQ,what do i need to do to talk to someone,CONTACT,contact_human_agent,Your input is valuable! I'm picking up that yo...
10,BMQ,have problems with creating my standard account,ACCOUNT,create_account,I'm sorry to hear that you're experiencing dif...
11,BKL,canceling {{Account Type}} account,ACCOUNT,delete_account,I'm glad you contacted us to us about cancelin...
12,BCIL,"I have to check the shipping methods, how can ...",DELIVERY,delivery_options,I'll take care of it! It's great to see your i...
13,BLQ,want help checking when will my product arrive,DELIVERY,delivery_period,We understand your eagerness to track your pro...
14,BL,I have got to change my personal information,ACCOUNT,edit_account,How wonderful it is to know that you're eager ...
15,BLM,help to get my bills from {{Person Name}},INVOICE,get_invoice,"Absolutely, I completely understand your need ..."
16,BLM,I don't know how to get compensations,REFUND,get_refund,I can sense that you are unsure about the proc...
17,BL,I want to sign up to your corporate newsletter,SUBSCRIPTION,newsletter_subscription,That's fantastic! I'm thrilled to hear that yo...
18,BMZ,help me to report issues with payment,PAYMENT,payment_issue,Absolutely! I'm here to assist you in reportin...
19,BILMQ,where can i order some of ur article,ORDER,place_order,I appreciate your interest in ordering some of...
20,BILQZ,can ya help me retrieve the pin code of my aco...,ACCOUNT,recover_password,We're here to help to us for assistance with r...
21,BCILQZ,wanna notify of an signup issue can uhelp me,ACCOUNT,registration_problems,Happy to get your message to us and notifying ...
22,BLQ,i want help leaving feedback about a service,FEEDBACK,review,We appreciate your intention to leave feedback...
23,BLQ,i have a problem setting up my secondary shipp...,SHIPPING,set_up_shipping_address,I hear you loud and clear that you're experien...
24,BIQ,how do i use the {{Account Type}} account,ACCOUNT,switch_account,Sure! I commend your interest in exploring the...
25,BL,see order {{Order Number}} status,ORDER,track_order,Thank you for reaching out! I completely under...
26,BLQ,I'm waiting for a compensation of {{Currency S...,REFUND,track_refund,I get it the importance of receiving your expe...

In [5]:
# %%
remaining = eval_df.drop(index=eval_set.index)

extra = remaining.sample(
    n=3,
    random_state=123
)

eval_set = pd.concat(
    [eval_set, extra],
    ignore_index=True
)

In [6]:
eval_set

,flags,instruction,category,intent,response
0,BELN,I cannot afford purchase {{Order Number}},ORDER,cancel_order,I understand the financial constraints you are...
1,BKL,modify order {{Order Number}},ORDER,change_order,Thank you for bringing up the request to modif...
2,BIL,where do I correct my address?,SHIPPING,change_shipping_address,"To update your shipping address, you can go to..."
3,BILMZ,where can I see the temrination fees?,CANCEL,check_cancellation_fee,"Sure, I can help you with finding information ..."
4,BLQZ,i dont know what i need to do to find ibll #12588,INVOICE,check_invoice,I've realized you're unsure about the steps to...
5,BL,show me your payment options,PAYMENT,check_payment_methods,For sure! It's my pleasure to assist you in ex...
6,BI,can you show me in what cases can I ask to be ...,REFUND,check_refund_policy,I'm on it! I completely understand your desire...
7,BL,help making a customer reclamation against you...,FEEDBACK,complaint,I apologize for any inconvenience you have exp...
8,BIL,can I contact customer assistance?,CONTACT,contact_customer_service,Thank you for reaching out! I completely under...
9,BILQ,what do i need to do to talk to someone,CONTACT,contact_human_agent,Your input is valuable! I'm picking up that yo...
10,BMQ,have problems with creating my standard account,ACCOUNT,create_account,I'm sorry to hear that you're experiencing dif...
11,BKL,canceling {{Account Type}} account,ACCOUNT,delete_account,I'm glad you contacted us to us about cancelin...
12,BCIL,"I have to check the shipping methods, how can ...",DELIVERY,delivery_options,I'll take care of it! It's great to see your i...
13,BLQ,want help checking when will my product arrive,DELIVERY,delivery_period,We understand your eagerness to track your pro...
14,BL,I have got to change my personal information,ACCOUNT,edit_account,How wonderful it is to know that you're eager ...
15,BLM,help to get my bills from {{Person Name}},INVOICE,get_invoice,"Absolutely, I completely understand your need ..."
16,BLM,I don't know how to get compensations,REFUND,get_refund,I can sense that you are unsure about the proc...
17,BL,I want to sign up to your corporate newsletter,SUBSCRIPTION,newsletter_subscription,That's fantastic! I'm thrilled to hear that yo...
18,BMZ,help me to report issues with payment,PAYMENT,payment_issue,Absolutely! I'm here to assist you in reportin...
19,BILMQ,where can i order some of ur article,ORDER,place_order,I appreciate your interest in ordering some of...
20,BILQZ,can ya help me retrieve the pin code of my aco...,ACCOUNT,recover_password,We're here to help to us for assistance with r...
21,BCILQZ,wanna notify of an signup issue can uhelp me,ACCOUNT,registration_problems,Happy to get your message to us and notifying ...
22,BLQ,i want help leaving feedback about a service,FEEDBACK,review,We appreciate your intention to leave feedback...
23,BLQ,i have a problem setting up my secondary shipp...,SHIPPING,set_up_shipping_address,I hear you loud and clear that you're experien...
24,BIQ,how do i use the {{Account Type}} account,ACCOUNT,switch_account,Sure! I commend your interest in exploring the...
25,BL,see order {{Order Number}} status,ORDER,track_order,Thank you for reaching out! I completely under...
26,BLQ,I'm waiting for a compensation of {{Currency S...,REFUND,track_refund,I get it the importance of receiving your expe...
27,BK,track order {{Order Number}},ORDER,track_order,Thank you for reaching out! I'm here to help y...
28,BLQZ,wanna check the status of my subscription to u...,SUBSCRIPTION,newsletter_subscription,I understand how important it is for you to st...
29,BZ,I need hepp using the standard account,ACCOUNT,switch_account,Unquestionably! I'm here to assist you in maki...

In [7]:
# %%
eval_set.insert(
    0,
    "query_id",
    [f"Q{i:02d}" for i in range(1, len(eval_set) + 1)]
)

In [8]:
eval_set

,query_id,flags,instruction,category,intent,response
0,Q01,BELN,I cannot afford purchase {{Order Number}},ORDER,cancel_order,I understand the financial constraints you are...
1,Q02,BKL,modify order {{Order Number}},ORDER,change_order,Thank you for bringing up the request to modif...
2,Q03,BIL,where do I correct my address?,SHIPPING,change_shipping_address,"To update your shipping address, you can go to..."
3,Q04,BILMZ,where can I see the temrination fees?,CANCEL,check_cancellation_fee,"Sure, I can help you with finding information ..."
4,Q05,BLQZ,i dont know what i need to do to find ibll #12588,INVOICE,check_invoice,I've realized you're unsure about the steps to...
5,Q06,BL,show me your payment options,PAYMENT,check_payment_methods,For sure! It's my pleasure to assist you in ex...
6,Q07,BI,can you show me in what cases can I ask to be ...,REFUND,check_refund_policy,I'm on it! I completely understand your desire...
7,Q08,BL,help making a customer reclamation against you...,FEEDBACK,complaint,I apologize for any inconvenience you have exp...
8,Q09,BIL,can I contact customer assistance?,CONTACT,contact_customer_service,Thank you for reaching out! I completely under...
9,Q10,BILQ,what do i need to do to talk to someone,CONTACT,contact_human_agent,Your input is valuable! I'm picking up that yo...
10,Q11,BMQ,have problems with creating my standard account,ACCOUNT,create_account,I'm sorry to hear that you're experiencing dif...
11,Q12,BKL,canceling {{Account Type}} account,ACCOUNT,delete_account,I'm glad you contacted us to us about cancelin...
12,Q13,BCIL,"I have to check the shipping methods, how can ...",DELIVERY,delivery_options,I'll take care of it! It's great to see your i...
13,Q14,BLQ,want help checking when will my product arrive,DELIVERY,delivery_period,We understand your eagerness to track your pro...
14,Q15,BL,I have got to change my personal information,ACCOUNT,edit_account,How wonderful it is to know that you're eager ...
15,Q16,BLM,help to get my bills from {{Person Name}},INVOICE,get_invoice,"Absolutely, I completely understand your need ..."
16,Q17,BLM,I don't know how to get compensations,REFUND,get_refund,I can sense that you are unsure about the proc...
17,Q18,BL,I want to sign up to your corporate newsletter,SUBSCRIPTION,newsletter_subscription,That's fantastic! I'm thrilled to hear that yo...
18,Q19,BMZ,help me to report issues with payment,PAYMENT,payment_issue,Absolutely! I'm here to assist you in reportin...
19,Q20,BILMQ,where can i order some of ur article,ORDER,place_order,I appreciate your interest in ordering some of...
20,Q21,BILQZ,can ya help me retrieve the pin code of my aco...,ACCOUNT,recover_password,We're here to help to us for assistance with r...
21,Q22,BCILQZ,wanna notify of an signup issue can uhelp me,ACCOUNT,registration_problems,Happy to get your message to us and notifying ...
22,Q23,BLQ,i want help leaving feedback about a service,FEEDBACK,review,We appreciate your intention to leave feedback...
23,Q24,BLQ,i have a problem setting up my secondary shipp...,SHIPPING,set_up_shipping_address,I hear you loud and clear that you're experien...
24,Q25,BIQ,how do i use the {{Account Type}} account,ACCOUNT,switch_account,Sure! I commend your interest in exploring the...
25,Q26,BL,see order {{Order Number}} status,ORDER,track_order,Thank you for reaching out! I completely under...
26,Q27,BLQ,I'm waiting for a compensation of {{Currency S...,REFUND,track_refund,I get it the importance of receiving your expe...
27,Q28,BK,track order {{Order Number}},ORDER,track_order,Thank you for reaching out! I'm here to help y...
28,Q29,BLQZ,wanna check the status of my subscription to u...,SUBSCRIPTION,newsletter_subscription,I understand how important it is for you to st...
29,Q30,BZ,I need hepp using the standard account,ACCOUNT,switch_account,Unquestionably! I'm here to assist you in maki...

In [9]:
print(eval_set.shape)
print(eval_set["intent"].nunique())

(30, 6)
27

In [10]:
# %%
eval_set = eval_set[
    [
        "query_id",
        "instruction",
        "intent",
        "category"
    ]
].copy()

In [11]:
eval_set

,query_id,instruction,intent,category
0,Q01,I cannot afford purchase {{Order Number}},cancel_order,ORDER
1,Q02,modify order {{Order Number}},change_order,ORDER
2,Q03,where do I correct my address?,change_shipping_address,SHIPPING
3,Q04,where can I see the temrination fees?,check_cancellation_fee,CANCEL
4,Q05,i dont know what i need to do to find ibll #12588,check_invoice,INVOICE
5,Q06,show me your payment options,check_payment_methods,PAYMENT
6,Q07,can you show me in what cases can I ask to be ...,check_refund_policy,REFUND
7,Q08,help making a customer reclamation against you...,complaint,FEEDBACK
8,Q09,can I contact customer assistance?,contact_customer_service,CONTACT
9,Q10,what do i need to do to talk to someone,contact_human_agent,CONTACT
10,Q11,have problems with creating my standard account,create_account,ACCOUNT
11,Q12,canceling {{Account Type}} account,delete_account,ACCOUNT
12,Q13,"I have to check the shipping methods, how can ...",delivery_options,DELIVERY
13,Q14,want help checking when will my product arrive,delivery_period,DELIVERY
14,Q15,I have got to change my personal information,edit_account,ACCOUNT
15,Q16,help to get my bills from {{Person Name}},get_invoice,INVOICE
16,Q17,I don't know how to get compensations,get_refund,REFUND
17,Q18,I want to sign up to your corporate newsletter,newsletter_subscription,SUBSCRIPTION
18,Q19,help me to report issues with payment,payment_issue,PAYMENT
19,Q20,where can i order some of ur article,place_order,ORDER
20,Q21,can ya help me retrieve the pin code of my aco...,recover_password,ACCOUNT
21,Q22,wanna notify of an signup issue can uhelp me,registration_problems,ACCOUNT
22,Q23,i want help leaving feedback about a service,review,FEEDBACK
23,Q24,i have a problem setting up my secondary shipp...,set_up_shipping_address,SHIPPING
24,Q25,how do i use the {{Account Type}} account,switch_account,ACCOUNT
25,Q26,see order {{Order Number}} status,track_order,ORDER
26,Q27,I'm waiting for a compensation of {{Currency S...,track_refund,REFUND
27,Q28,track order {{Order Number}},track_order,ORDER
28,Q29,wanna check the status of my subscription to u...,newsletter_subscription,SUBSCRIPTION
29,Q30,I need hepp using the standard account,switch_account,ACCOUNT

In [12]:
# %%
eval_set = eval_set[
    [
        "query_id",
        "instruction",
        "intent",
        "category"
    ]
].copy()

In [13]:
eval_set.head()

,query_id,instruction,intent,category
0,Q01,I cannot afford purchase {{Order Number}},cancel_order,ORDER
1,Q02,modify order {{Order Number}},change_order,ORDER
2,Q03,where do I correct my address?,change_shipping_address,SHIPPING
3,Q04,where can I see the temrination fees?,check_cancellation_fee,CANCEL
4,Q05,i dont know what i need to do to find ibll #12588,check_invoice,INVOICE

In [14]:

eval_set.to_csv(
    "eval_set.csv",
    index=False
)

In [15]:
eval_set.shape

(30, 4)